---
- hosts: all
  ignore_errors: yes
  become: yes
  tasks:
        - name: create user
          user:
                name: Ewane
                comment: Ewane Ayissi

        - name: create directory
          file:
                path: /tmp/devops-ans
                owner: Ewane
                mode: "0777"
                state: directory

        - name: create file
          file:
                path: /tmp/ansible-class
                owner: Ewane
                mode: "0600"
                state: touch 
